library(ggplot2)
library(ggmap)
library(maps)
library(mapdata)
library(readr)
library(dplyr)
library(tidyr)
library(ggrepel)
library(jsonlite)

options(scipen = 999)


#ensures seed so lines are always generated at the same spot
set.seed(42)

filter <- function(data, field, from, to){
  return(data[which(field>=from & field <= to),])
}

dateFrom <- as.character('2020-01-01')
dateTo <- as.character('2020-05-31')

#read data generated by python script (google maps data)
activities <- read_csv("data/activities.csv")

filtered_data <- select(filter(activities, activities$Time, dateFrom, dateTo), Activity, GroupID, Lat, Lng, Alt)
filtered_data <- filtered_data[filtered_data$Activity == "Running" | filtered_data$Activity == "Biking" | filtered_data$Activity == "Inline skating", ]

bbox_fence <- make_bbox(lat = Lat, lon = Lng, data = filtered_data)


gbase <- ggplot(data = filtered_data) 

#load google map area
gm <- get_map(location = bbox_fence, source = "google", maptype="terrain")

ggmap(gm, base_layer = gbase) + geom_path(data = filtered_data, aes(x=Lng, y=Lat, group=GroupID, color=Activity), size = 1.5, lineend = "round") + 
  labs(x="", y="", color="Activity", title = "All activities", subtitle = paste(dateFrom, "to", dateTo))

ggsave(paste("movements-", dateFrom, "-", dateTo, ".png", sep = ""), width = 12, height = 12, units = "in")
